Supress all warnings from urllib3
* In Raspbian, previous code fails to run bellow error
* I decide to supress all warnings instead of doing only InsecureRequestWarning

``` log
  File "/dash-ha.py", line 6, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning
```